### ISSUE TITLE
Not able to scroll the State pane

### ISSUE THREAD

**Issue by jombie** [zalmoxisus/redux-devtools-extension#263]
The State>Tree pane is not scrollbable, so not able to see complete state.
![redux-dev-tools](https://cloud.githubusercontent.com/assets/2740421/20639557/42e571a0-b3ed-11e6-8ac5-66f56d31d3b0.png)

**Comment by zalmoxisus** [comment]
It was just fixed by @jhen0409 in https://github.com/zalmoxisus/remotedev-monitor-components/pull/1. The patch be available on Chrome Store in about an hour.

Thanks for the report!

**Comment by zalmoxisus** [comment]
Available in `2.11.0.2`. Feel free to reopen the issue if it still goes wrong.

**Comment by jombie** [comment]
Still not working for me, Here are the screenshots let me know if i need to change something

![redux-3](https://cloud.githubusercontent.com/assets/2740421/20640978/b2824198-b413-11e6-9fc4-90ae8632f6e3.png)
![redux-2](https://cloud.githubusercontent.com/assets/2740421/20640979/b2847d1e-b413-11e6-82dc-9e90e0fdd71f.png)

**Comment by zalmoxisus** [comment]
@jombie you can check the installed version on `chrome://extensions` page (or click on the extension `Settings` button and you'll get there). It should be `2.11.0.2`.

**Comment by jasondonnette** [comment]
@zalmoxisus I'm on 2.11.0.3 and it still seems broken on OSX and Chrome 54.0.2840.98

**Comment by zalmoxisus** [comment]
Weird, indeed I didn't updated that. Just uploaded `2.11.0.4`. It will be available in about an hour on Chrome store. Sorry for the troubles 😕
