### ISSUE TITLE
Get following error "TypeError: cannot use the given object as a weak map key" when devtools is opened

### ISSUE THREAD

**Issue by podeig** [zalmoxisus/redux-devtools-extension#574]
Hi,

**I get "TypeError: cannot use the given object as a weak map key" error which is coming up when the first actions is initiated by user. The whole web solution crashes. Without devtools everything works fine.**

My setup:
    "react": "^16.6.0",
    "react-dom": "^16.6.0",
    "react-redux": "^5.1.0",
    "redux-persist": "^5.10.0",
    "redux-saga": "^0.16.2",
    "typescript": "^3.1.6"

The full error log:

**TypeError: cannot use the given object as a weak map key**

derez
http://localhost:3000/:1:65994
derez
http://localhost:3000/:1:66278
derez
http://localhost:3000/:1:66278
derez
http://localhost:3000/:1:66278
derez
http://localhost:3000/:1:66278
derez
http://localhost:3000/:1:66278
derez
http://localhost:3000/:1:66096
derez
http://localhost:3000/:1:66278
derez
http://localhost:3000/:1:66278
derez
http://localhost:3000/:1:66096
derez
http://localhost:3000/:1:66278
derez
http://localhost:3000/:1:66096
derez
http://localhost:3000/:1:66278
derez
http://localhost:3000/:1:66096
derez
http://localhost:3000/:1:66278
derez
http://localhost:3000/:1:66096
derez
http://localhost:3000/:1:66278
derez
http://localhost:3000/:1:66278
derez
http://localhost:3000/:1:66278
derez
http://localhost:3000/:1:66278
derez
http://localhost:3000/:1:66278
derez
http://localhost:3000/:1:66278
derez
http://localhost:3000/:1:66278
decycle
http://localhost:3000/:1:64661
e.stringify
http://localhost:3000/:1:19674
tryCatchStringify
http://localhost:3000/:1:68817
stringify
http://localhost:3000/:1:68935
toContentScript
http://localhost:3000/:1:69968
relay
http://localhost:3000/:1:23194
E/q<
http://localhost:3000/:1:26558
invokeFunc
http://localhost:3000/:1:29787
leadingEdge
http://localhost:3000/:1:29866
debounced
http://localhost:3000/:1:30443
handleChange
http://localhost:3000/:1:25120
dispatch
node_modules/redux/es/redux.js:221

  218 | var listeners = currentListeners = nextListeners;
  219 | for (var i = 0; i < listeners.length; i++) {
  220 |   var listener = listeners[i];
> 221 |   listener();
  222 | }
  223 | 
  224 | return action;

dispatch
http://localhost:3000/:1:38397
sagaMiddleware/</<
node_modules/redux-saga/es/internal/middleware.js:66

  63 |   if (sagaMonitor && sagaMonitor.actionDispatched) {
  64 |     sagaMonitor.actionDispatched(action);
  65 |   }
> 66 |   var result = next(action); // hit reducers
  67 |   sagaEmitter.emit(action);
  68 |   return result;
  69 | };

asyncActions/</<
src/StoreSetup.tsx:24

  21 | 
  22 | // Async middleware to support asynchronous actions
  23 | export const asyncActions = (api: any) => (next: any) => {
> 24 |     return (action: any) => typeof action === 'function' ? action(api.dispatch) : next(action);
  25 | };
  26 | 
  27 | // create the saga middleware

dispatch
node_modules/redux/es/redux.js:563
uiConfig/<
src/actions/UiActions.tsx:23

  20 | export type UiAction = UiConfig | UiMapPadding;
  21 | 
  22 | export const uiConfig = (panels: {}): any => (dispatch: Dispatch) => {
> 23 |     dispatch({
  24 |         type: constants.UI_CONFIG,
  25 |         panels
  26 |     });

asyncActions/</<
src/StoreSetup.tsx:24

  21 | 
  22 | // Async middleware to support asynchronous actions
  23 | export const asyncActions = (api: any) => (next: any) => {
> 24 |     return (action: any) => typeof action === 'function' ? action(api.dispatch) : next(action);
  25 | };
  26 | 
  27 | // create the saga middleware

uiConfig
src/components/mainmenu/MainMenu.tsx:210

  207 | 
  208 | export function mapDispatchToProps(dispatch: Dispatch<actions.UiAction>): DispatchProps {
  209 |     return {
> 210 |         uiConfig: (
  211 |             panels: {
  212 |                 main: {
  213 |                     extended: boolean;

./src/components/mainmenu/MainMenu.tsx/MainMenu</MainMenu.prototype.switchMenuSelectedItem
src/components/mainmenu/MainMenu.tsx:93

  90 | }
  91 | 
  92 | switchMenuSelectedItem(mainMenuItem: MainMenuItems) {
> 93 |     this.props.uiConfig(
  94 |         {
  95 |             main: {
  96 |                 extended: true,

onClick
src/components/mainmenu/MainMenu.tsx:142

  139 | return (
  140 |     <ul className="getMainMenuSelection">
  141 |     <li className={classNames('getMenuItemList', { 'selected': mainActiveItem === MainMenuItems.List })}>
> 142 |         <a onClick={() => this.switchMenuSelectedItem(MainMenuItems.List)} />
  143 |     </li>
  144 |     <li className={classNames('getMenuItemCalendar', { 'selected': mainActiveItem === MainMenuItems.Calendar })}>
  145 |         <a onClick={() => this.switchMenuSelectedItem(MainMenuItems.Calendar)} />

Thanks!

**Comment by zalmoxisus** [comment]
Was it on Firefox? If so, could you please confirm that it was the same as reported in #573 and fixed in last version?

**Comment by zalmoxisus** [comment]
Could be related to https://bugzilla.mozilla.org/show_bug.cgi?id=1351501, but need an example to reproduce.

**Comment by podeig** [comment]
> Was it on Firefox? If so, could you please confirm that it was the same as reported in #573 and fixed in last version?

I do not think that it is the same issue. 
Yes, errors still come in Firefox, but both Firefox and Chrome redux store is been initialisert, but it just crushes after the first changes in the store.
